language : java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Home
cache :
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script : "./gradlew clean build"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket:  spring-webservice-by-enhakkore-deploy
    region : ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: enhakkore/spring-webservice
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ahn.ephraim@gmail.com